backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

title: &title
  label: "Title"
  name: "title"
  widget: "string"

body: &body
  label: "Body"
  name: "body"
  widget: "markdown"

backgroundImage: &backgroundImage
  label: "Background Image"
  name: "backgroundImage"
  widget: "image"

button: &button
  label: "Button"
  name: "button"
  widget: "object"
  fields:
    - {label: "Text", name: "children", widget: "string"}
    - {label: "URL", name: "href", widget: "string"}
    - {label: "Background Color", name: "background", widget: "color"}
    - {label: "Text Color", name: "color", widget: "color"}

collections:
  - name: "pages"
    label: "Pages"
    delete: false
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "homepage"}
          - {label: "Logo", name: "logo", widget: "image"}
          - label: "Join Us"
            name: "joinUs"
            widget: "object"
            fields:
              - <<: *title
              - <<: *backgroundImage
              - <<: *button
              - {label: "Logo", name: "logo", widget: "image"}
          - label: "Economy"
            name: "economy"
            widget: "object"
            fields:
              - <<: *title
              - <<: *backgroundImage
              - {label: "Upper Text", name: "upperText", widget: "text"}
              - label: "Columns"
                name: "columns"
                widget: "list"
                fields:
                  - <<: *title
                  - <<: *body
              - {label: "Lower Text", name: "lowerText", widget: "text"}
              - label: "Whitepaper Button"
                name: "button"
                widget: "object"
                fields:
                  - {label: "Text", name: "children", widget: "string"}
                  - {label: "File", name: "href", widget: "file"}
                  - {label: "Background Color", name: "background", widget: "color"}
                  - {label: "Text Color", name: "color", widget: "color"}
          - label: "FAQ"
            name: "faq"
            widget: "object"
            fields:
              - <<: *title
              - <<: *backgroundImage
              - label: "Questions"
                name: "questions"
                widget: "list"
                fields:
                  - {label: "Question", name: "question", widget: "string"}
                  - {label: "Answer", name: "answer", widget: "text"}
          - label: "Product"
            name: "product"
            widget: "object"
            fields:
              - <<: *title
              - {label: "Secondary Title", name: "subtitle", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - <<: *body
              - label: "Panels"
                name: "panels"
                widget: "list"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "URL", name: "url", widget: "string"}
          - label: "Perks"
            name: "perks"
            widget: "object"
            fields:
              - <<: *title
              - label: "Columns"
                name: "columns"
                widget: "list"
                fields:
                  - <<: *title
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Text", name: "text", widget: "string"}
          - label: "Company"
            name: "company"
            widget: "object"
            fields:
              - <<: *title
              - <<: *body
              - {label: "Logo", name: "logo", widget: "image"}
              - label: "Panels"
                name: "panels"
                widget: "list"
                fields:
                  - <<: *title
                  - {label: "Progress", name: "progress", widget: "number"}
                  - {label: "Text", name: "text", widget: "text"}
          - label: "DPoS"
            name: "dpos"
            widget: "object"
            fields:
              - <<: *title
              - <<: *body
              - <<: *backgroundImage
              - <<: *button
          - label: "Newsletter"
            name: "newsletter"
            widget: "object"
            fields:
              - <<: *title
              - <<: *backgroundImage
          - label: "Roadmap"
            name: "roadmap"
            widget: "object"
            fields:
              - <<: *title
              - label: "Events"
                name: "events"
                widget: "list"
                fields:
                  - {label: "Date", name: "date", widget: "date", format: "DD MMM YYYY"}
                  - {label: "Text", name: "text", widget: "text"}
                  - {label: "Is in past?", name: "past", widget: "boolean"}
          - label: "Distribution"
            name: "distribution"
            widget: "object"
            fields:
              - <<: *title
              - label: "Distribution"
                name: "distribution"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Percentage", name: "value", widget: "number"}
                  - {label: "Color", name: "color", widget: "color"}
              - label: "Tranches"
                name: "tranches"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Percentage", name: "value", widget: "number"}
          - label: "Team"
            name: "team"
            widget: "object"
            fields:
              - <<: *title
              - label: "Members"
                name: "members"
                widget: "list"
                fields:
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Description", name: "description", widget: "string"}
          - label: "Partners"
            name: "partners"
            widget: "object"
            fields:
              - <<: *title
              - label: "Partners"
                name: "partners"
                widget: "list"
                field:
                  - {label: Image, name: image, widget: image}
                  - {label: URL, name: href, widget: string}
          - label: "Contact"
            name: "contact"
            widget: "object"
            fields:
              - <<: *title
              - {label: "Address", name: "address", widget: "string"}
              - label: "Social Links"
                name: "socialLinks"
                widget: "list"
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: "URL", name: "href", widget: "string"}
          - {label: "Copyright", name: "copyright", widget: "string"}
